### ISSUE TITLE
Build depending on source code only

### ISSUE THREAD

**Issue by edward-ji** [Quark-Games/YEquals#32]
Build process should not run on all file changes (e.g. 385f514dd41e98046c9ec1cc6830b1348e4773d1)

Instead of running on all push and pull requests, we should specify file paths in the workflow files.

Add something like the following in `.github/workflows/release.yml`
```
on:
  push:
    branches: [ master ]
    paths:
      - '*.py'
      - 'assets/**'
```
